import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import Storeprovider from "@/lib/utils/Storeprovider";
import Header from "./components/header/Header";
import Sidebar from "./components/sidebar/Sidebar";
import Footer from "./components/footer/Footer";
export const metadata = {
  title: "Next Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <Storeprovider>
    <html lang="en">
      <body className="flex">
        <Sidebar/>
        <main className="flex-1 bg-blue-50">

        <Header/>
        {
          children
        }
        <Footer/>
        </main>
      </body>
    </html>
        </Storeprovider>
  );
}
