import { Inter } from "next/font/google";
import "./globals.css";
import Storeprovider from "@/lib/utils/Storeprovider";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import Footer from "./components/Footer";
import Authprovider from "@/auth-provider/Authprovider";
import {Toaster} from 'react-hot-toast'
export const metadata = {
  title: "Next Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Authprovider>
      <Storeprovider>
        <html lang="en">
          <body className="overflow-x-hidden bg-primaryClr">
            <Toaster/>
            <Header />
            <main className="flex">
              <Sidebar />
              <div className="flex-1">{children}</div>
            </main>
            <Footer />
          </body>
        </html>
      </Storeprovider>
    </Authprovider>
  );
}
